language: python


python:
    - "2.7"

sudo: required

services:
    - docker

notifications:
  email:
    recipients:
      - arfathpasha@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    # TEST_USER
    #- secure: "Yj5naQWntR9Mjc41USqNepyicl/e2/ARKBowdaVfF/pZ+rMrhOk0IgeH+cpqhrUdnDlAG7GHsOfvqP4eYGId3xJHT/YQQm2Ss+9OOaNq4/obufzxmxuMlLXzWjsQCOUw+TIK0Tvi+PELeqTkqg6HBiWJX/eUYVNjyp8lG16wGmAIwHlfqXdzyD7RXX87hlzNff4kIybcdG9qJctrrFbJfENOW1NocktUn6Pv095v4R41Nw/xR//F42eu9gv+LTkRUw0CBs2ih3DEjgAeUQN0fYV/pgsIxCe3LWK6cJH7J0D/Vge1ZknTdVynD9t2freyM4/Qa61Hi47s9zSTOPDg2NeJRbmgaGCQcwiN47ahsbdWuxpkU4tok/yWKAdiQckkRg+P0vUGrj/C/eu1mW6EwY/52WqW+afW48wAKzuUuRH0jKJtYaQtfagIdhH++0GxEAn5bscnk/8V/IKytKWLkC0KQDsbx54wkPoxXu87iSXlOw6JYQsbgEL2SU/HqZCv/R+pOePu/z9Bzcged0geykK7NvCrgCccsmFeCHpNpIaR5qXmLTabIsjdQIGhGPK4RMCFs1DFYxjGKX3BTEVcsrDK1RSHyFKFY5AlkeZI+2jfR0y0mTwf+6ckKnGaENUuC7HL2G+JRJIiDD5gSMUZ/fciaBXix3F4I8skMt+iF/4="
    # TEST_PASSWORD
    #- secure: "V8TuLmNg7n/fzdOkv3hcd/TFzexKRmrjBmFmlMqSXXbG3A1BlkIJOdhDLWjxKiWVGLOENXkiBd9CPOEKwZnJAfoOm3hdpZ3tTrsGqL/0DTCgwmP8Uj1RZ8zt5hYu4IfTnJHLJmNEzwfZ29eC1ONhsSXp9ATbG7lyI2BqFchwnOFGcg03CJ5fl+CJAucrJta/uHNaRXRpnf33DG3M105X/V7WdzNDIfQBCLgx+ZyuvQo0AxZpDy9+iRFqt0cNfhAsYKnsLFJ+VSv+4Fzj+a+uGnXLz/jLFJCSt3Z9CuOuuiepCjkFAgMuJ6W58C6M/0t8/ixPeeVKs7acIKnaTKJ7B8MPM/O1Y3GMdpS+elwLWV1Z9Ku3V3suSMcYv+PeErN78+vGVR/iH/zw8mue+1yxQvBPMjl/zVmgHgG3YOevHKu/RUNLLVMt+/jrHGe2+HqHIIdejO1dwOWDDfstsVRGbpFU8VXQplM7+3iSe6q7aY07ZsRgDzk2SHI2cCg0Th5lUp8ri2oeMaAuFJSD2nWpT0bvull1jNoYRK4/h/3Pam2Hw64CQr2wIMhLBAfeVcvhLaNaVi8wCWxTHyHJ0cDpTd307mqnsuU+HIfmVzatYpXM7RXJXvYcAxfmRnKh9xOsNRyetyFbfmuzLTEedMYMT5Q6J7v5DORDzpU5F8kklA0="
    # TEST_TOKEN
    secure: "ihFDDlgYx5W8tvBSqw9v4cn9Ejw2VTSHH3Hu8C+mpufJwNavbKk8C5ttezzem/2ltQbgH79L+TNCh55GW2dURVCLvP68LkjTfOIfCToS8YBGJXdDBOhy4uWKSrKjwPpl48InN7H94thchl3vFjoX158yv+Vneh8/jMFjzbguhSncSMNIBAnEtYyIlJDGXRXyLgPP79iAuC7vnOwfJXnj7+TobNx7bSaGtYy3FlmP4DRDGSBWx5a0hgZUuZMifclcx2+2/pEGU+8xGsnjxGdkY7xnyTQrCc0ZxlLYCRpyupmPXls1tYBwtyDvd0wnjiNCWg2vPTiaRxOWB/jp4HOxF79OskYvWCNTEkj/jfrI8kl0mbkG9jFn8SjNnAlLbrApgHDdTpLtMfKjYpbVRpJAkUH+aL43EhR/BTTzd/P40tu/7qnnLAwLAoRgOUG0iaolvwN0LzOTbr+MyriV/elIi1bMh2NSs7Ts9Dt8o1WvCyga+6WRZUMOnICtxN6kAJkARdALNIsjHr559inNtuAVX7DmAN5eCMbmY4upVrJiWxzPasI+nXifl4MQmK2x7EIXfkadagtibMgq5hVy0xQuzzYRr9yQsejGml8MH2xt7e4r2iWjqBxMMw6GBLHGYMdHSaFcTsETua8cB/335rXtaFuwd9saw61rvdnlunh8nmg="

branches:
  only:
    - travis

before_install:
    - docker version
    - python --version

install:
    - pip install coveralls
    - pip install coverage
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - make sdkbase
    - docker images
    - export PATH=$(pwd)/bin:$PATH
    - cd ../
    #IMPORTANT change clone to kbaseapps and finally to kbase after pull requests
    - git clone git@github.com:arfathpasha/ReadsAlignmentUtils.git
    - cd ReadsAlignmentUtils
    # run the kb-sdk test command once to build test_local dir and populate the .ignore files
    - kb-sdk test -s || true
    # add test config
    #- sed -i "s/test_user=/test_user=$TEST_USER/" test_local/test.cfg
    #- sed -i "s/test_password=/test_password=$TEST_PASSWORD/" test_local/test.cfg
    - sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
    - sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
    - sed -i 's\https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\' test_local/test.cfg
    - cat test_local/test.cfg

script:
    - kb-sdk test

after_success:
    - cp test_local/workdir/.coverage .
    - sudo mkdir -p /kb/deployment
    - sudo cp -R test_local/workdir/kb/deployment/lib /kb/deployment
    - ls -l /kb/deployment/lib/biokbase/
    - coverage report -m
    - coveralls
